import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layout/footer/Footer';
import Navbar from '@/components/layout/navbar/Navbar';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={lexend.className}>
                <Navbar/>
                <div className="min-h-[100vh]">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
