import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Layout/Footer/Footer';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={lexend.className}>
                <div className="px-[5%] sm:px-[10%] lg:px-[15%]">{children}</div>
                <Footer/>
            </body>
        </html>
    );
}
