#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '⚙️ 🛠️  Running pre-commit checks: Styling, linting, and type-checking your project, Please wait...'

# Run Prettier to check code formatting
npm run prettier || (
    echo '❌ Prettier Check Failed. Please run `npm run prettier`, fix any issues, and try committing again.'
    false
)

# Run ESLint to check for code quality and style issues
npm run lint || (
    echo '❌ ESLint Check Failed. Please address the issues listed above, fix them, and try committing again.'
    false
)

# Run TypeScript to check for type errors
npm run check-types || (
    echo '❌ TypeScript Check Failed. Please fix the type errors listed above and try committing again.'
    false
)

# Run Commitlint to enforce commit message conventions
npm run commitlint || (
    echo '❌ Commitlint Check Failed. Please fix your commit message to match the required format and try again.'
    false
)

# If everything passes, proceed with the commit
echo '✅ All checks passed! Committing your changes... ✅'
